version: '3.7'
services:
  elasticsearch:
    container_name: seaq_local
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
    networks:
      - seaq_local_network
  kibana:
    container_name: kb_kibana
    image: docker.elastic.co/kibana/kibana:7.16.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://seaq_local:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    networks:
      - seaq_local_network
  apm:
    container_name: seaq_apm
    image: docker.elastic.co/apm/apm-server:7.16.1
    ports:
      - 8200:8200
    command: >
      apm-server -e
      -E output.elasticsearch.hosts=["seaq_local:9200"]
      -E output.elasticsearch.protocol=http
      -E output.elasticsearch.username=elastic
      -E output.elasticsearch.password=elastic
      -E apm-server.secret_token=lRiDTwv2dis5J53dke
      -E setup.kibana.host=seaq_kibana:5601
      -E apm-server.kibana.enabled=true
      -E apm-server.kibana.host=seaq_kibana:5601
      -E apm-server.kibana.protocol=http
      -E apm-server.kibana.username=elastic
      -E apm-server.kibana.password=elastic
      
      -E apm-server.auth.anonymous.enabled=true
      -E apm-server.auth.allow_agent=["dotnet","rum-js","js-base"]
      -E apm-server.auth.rate_limit.event_limit=100
      -E apm-server.rum.enabled=true
    networks:
      - seaq_local_network

networks:
  seaq_local_network: