version: '3.7'
services:
  elasticsearch:
    container_name: seaq_local
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - seaq_local_network
  kibana:
    container_name: kb_kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://seaq_local:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    networks:
      - seaq_local_network
  apm:
    container_name: seaq_apm
    image: docker.elastic.co/apm/apm-server:7.15.0
    ports:
      - 8200:8200
    environment:
      - output.elasticsearch.hosts=["seaq_local:9200"]
      - apm-server.secret_token=thisisasecret
    networks:
      - seaq_local_network

networks:
  seaq_local_network: