version: '3.7'
services:
  elasticsearch:
    container_name: seaq_6x_local
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.18
    ports:
      - 19200:9200
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - seaq_local_network_6x
  kibana:
    container_name: seaq_6x_kibana
    image: docker.elastic.co/kibana/kibana:6.8.18
    ports:
      - 15601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://seaq_6x_local:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    networks:
      - seaq_local_network_6x
  apm:
    container_name: seaq_6x_apm
    image: docker.elastic.co/apm/apm-server:6.8.18
    ports:
      - 18200:8200
    command: >
      apm-server -e
      -E output.elasticsearch.hosts=["seaq_6x_local:9200"]
      -E output.elasticsearch.protocol=http
      -E output.elasticsearch.username=elastic
      -E output.elasticsearch.password=elastic
      -E apm-server.secret_token=thisisasecret
      -E setup.kibana.host=seaq_6x_kibana:5601
      -E apm-server.kibana.enabled=true
      -E apm-server.kibana.host=seaq_6x_kibana:5601
      -E apm-server.kibana.protocol=http
      -E apm-server.kibana.username=elastic
      -E apm-server.kibana.password=elastic
    networks:
      - seaq_local_network_6x

networks:
  seaq_local_network_6x: